# Generated by Django 5.2.12 on 2026-03-13 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='investigati_email_eaec71_idx')],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('folder', models.CharField(blank=True, max_length=255)),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigation.email')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='investigation.person')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('to', 'To'), ('cc', 'Cc'), ('bcc', 'Bcc')], max_length=3)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='investigation.email')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigation.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['date'], name='investigati_date_f9d029_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['from_person'], name='investigati_from_pe_5ffef3_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['email', 'person'], name='investigati_email_i_f4253e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together={('email', 'person', 'type')},
        ),
    ]
