# Generated by Django 5.2.12 on 2026-03-16 11:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='email',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='investigati_search__51d018_gin'),
        ),
    ]
